# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=150, verbose_name=b'Item')),
                ('done', models.BooleanField(default=False, verbose_name=b'Done')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=150, verbose_name=b'List Name')),
                ('description', models.TextField(max_length=300, verbose_name=b'Description')),
                ('status', models.IntegerField(choices=[(1, b'Active'), (2, b'Finished'), (3, b'Removed')], default=1, verbose_name=b'Status')),
            ],
            options={
                'verbose_name': 'List',
                'verbose_name_plural': 'Lists',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='List',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.List'),
        ),
    ]
