# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='List',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
